name: my_apps
description: "Mys Application Android"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  get: ^4.6.6
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.20.2
  curved_navigation_bar: 1.0.6
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
